//
//  AniseekrCloudKitBridge.swift
//  AniSeekr
//
//  Bidirectional bridge between the React Native JS layer and the user's
//  private CloudKit database. Exposes three operations to JS:
//
//    isAvailable()                  -> Bool
//    fetchAllRecords()              -> [{recordType, recordName, fields}]
//    writeRecords([{...}])          -> {written, failed}
//    deleteAllRecords()             -> {deleted}
//
//  The same container ({{ICLOUD_CONTAINER}}) is shared with the legacy SwiftUI
//  aniseeker app, so its data is readable here as-is, and our writes are
//  visible there.
//
//  Generated by plugins/with-cloudkit-bridge.js — do not edit by hand in the
//  Xcode project; edit the template under plugins/templates/ instead.

import Foundation
import CloudKit
import React

@objc(AniseekrCloudKitBridge)
class AniseekrCloudKitBridge: NSObject {

  // Record types we expose. Must mirror Schema+V2.swift @Model class names
  // in the legacy aniseeker. Keep in sync with libs/services/backup/cloudkit-converter.ts.
  private static let recordTypes = [
    "UserRating",
    "TrackingAnime",
    "WatchedAnime",
    "WishlistItem",
    "CollectionFolder"
  ]

  private static let containerIdentifier = "{{ICLOUD_CONTAINER}}"

  private var container: CKContainer {
    return CKContainer(identifier: Self.containerIdentifier)
  }

  private var privateDB: CKDatabase {
    return container.privateCloudDatabase
  }

  @objc static func requiresMainQueueSetup() -> Bool { return false }

  // MARK: - Availability

  @objc(isAvailable:rejecter:)
  func isAvailable(_ resolve: @escaping RCTPromiseResolveBlock,
                   rejecter reject: @escaping RCTPromiseRejectBlock) {
    container.accountStatus { status, error in
      if let error = error {
        reject("ck_status_error", error.localizedDescription, error)
        return
      }
      resolve(status == .available)
    }
  }

  // MARK: - Fetch

  @objc(fetchAllRecords:rejecter:)
  func fetchAllRecords(_ resolve: @escaping RCTPromiseResolveBlock,
                       rejecter reject: @escaping RCTPromiseRejectBlock) {
    var collected: [[String: Any]] = []
    let group = DispatchGroup()
    var firstError: Error?

    for type in Self.recordTypes {
      group.enter()
      let query = CKQuery(recordType: type, predicate: NSPredicate(value: true))
      let operation = CKQueryOperation(query: query)
      operation.resultsLimit = CKQueryOperation.maximumResults

      if #available(iOS 15.0, *) {
        operation.recordMatchedBlock = { recordID, result in
          switch result {
          case .success(let record):
            collected.append(Self.encodeRecord(record))
          case .failure:
            break // skip individual record errors
          }
        }
        operation.queryResultBlock = { result in
          if case .failure(let err) = result, firstError == nil {
            firstError = err
          }
          group.leave()
        }
      } else {
        operation.recordFetchedBlock = { record in
          collected.append(Self.encodeRecord(record))
        }
        operation.queryCompletionBlock = { _, error in
          if let error = error, firstError == nil { firstError = error }
          group.leave()
        }
      }
      privateDB.add(operation)
    }

    group.notify(queue: .main) {
      if let err = firstError {
        reject("ck_fetch_failed", err.localizedDescription, err)
        return
      }
      resolve(collected)
    }
  }

  // MARK: - Write

  @objc(writeRecords:resolver:rejecter:)
  func writeRecords(_ records: NSArray,
                    resolver resolve: @escaping RCTPromiseResolveBlock,
                    rejecter reject: @escaping RCTPromiseRejectBlock) {
    let ckRecords: [CKRecord] = records.compactMap { raw in
      guard let dict = raw as? [String: Any],
            let recordType = dict["recordType"] as? String,
            let recordName = dict["recordName"] as? String,
            let fields = dict["fields"] as? [String: Any] else { return nil }
      let recordID = CKRecord.ID(recordName: recordName)
      let record = CKRecord(recordType: recordType, recordID: recordID)
      for (key, value) in fields {
        if let v = Self.encodeFieldValue(value) {
          record[key] = v
        }
      }
      return record
    }

    let op = CKModifyRecordsOperation(recordsToSave: ckRecords, recordIDsToDelete: nil)
    op.savePolicy = .changedKeys
    op.qualityOfService = .userInitiated

    var saved = 0
    var failed = 0

    if #available(iOS 15.0, *) {
      op.perRecordSaveBlock = { _, result in
        switch result {
        case .success: saved += 1
        case .failure: failed += 1
        }
      }
      op.modifyRecordsResultBlock = { result in
        switch result {
        case .success:
          resolve(["written": saved, "failed": failed])
        case .failure(let err):
          reject("ck_write_failed", err.localizedDescription, err)
        }
      }
    } else {
      op.modifyRecordsCompletionBlock = { savedRecords, _, error in
        if let error = error {
          reject("ck_write_failed", error.localizedDescription, error)
          return
        }
        saved = savedRecords?.count ?? 0
        resolve(["written": saved, "failed": failed])
      }
    }
    privateDB.add(op)
  }

  // MARK: - Delete all

  @objc(deleteAllRecords:rejecter:)
  func deleteAllRecords(_ resolve: @escaping RCTPromiseResolveBlock,
                        rejecter reject: @escaping RCTPromiseRejectBlock) {
    var idsToDelete: [CKRecord.ID] = []
    let group = DispatchGroup()
    var firstError: Error?

    for type in Self.recordTypes {
      group.enter()
      let query = CKQuery(recordType: type, predicate: NSPredicate(value: true))
      let operation = CKQueryOperation(query: query)
      if #available(iOS 15.0, *) {
        operation.recordMatchedBlock = { recordID, result in
          if case .success = result { idsToDelete.append(recordID) }
        }
        operation.queryResultBlock = { result in
          if case .failure(let err) = result, firstError == nil { firstError = err }
          group.leave()
        }
      } else {
        operation.recordFetchedBlock = { record in
          idsToDelete.append(record.recordID)
        }
        operation.queryCompletionBlock = { _, error in
          if let error = error, firstError == nil { firstError = error }
          group.leave()
        }
      }
      privateDB.add(operation)
    }

    group.notify(queue: .main) {
      if let err = firstError {
        reject("ck_delete_query_failed", err.localizedDescription, err)
        return
      }
      let op = CKModifyRecordsOperation(recordsToSave: nil, recordIDsToDelete: idsToDelete)
      if #available(iOS 15.0, *) {
        op.modifyRecordsResultBlock = { result in
          switch result {
          case .success: resolve(["deleted": idsToDelete.count])
          case .failure(let err): reject("ck_delete_failed", err.localizedDescription, err)
          }
        }
      } else {
        op.modifyRecordsCompletionBlock = { _, _, error in
          if let error = error {
            reject("ck_delete_failed", error.localizedDescription, error)
            return
          }
          resolve(["deleted": idsToDelete.count])
        }
      }
      self.privateDB.add(op)
    }
  }

  // MARK: - Encoding helpers

  private static func encodeRecord(_ record: CKRecord) -> [String: Any] {
    var fields: [String: Any] = [:]
    for key in record.allKeys() {
      if let v = record[key] {
        fields[key] = decodeFieldValue(v) ?? NSNull()
      }
    }
    return [
      "recordType": record.recordType,
      "recordName": record.recordID.recordName,
      "fields": fields
    ]
  }

  private static func decodeFieldValue(_ value: CKRecordValue) -> Any? {
    if let s = value as? String { return s }
    if let n = value as? NSNumber { return n }
    if let d = value as? Date { return d.timeIntervalSince1970 * 1000 }
    if let ref = value as? CKRecord.Reference { return ref.recordID.recordName }
    if let data = value as? Data { return data.base64EncodedString() }
    if let arr = value as? [Any] {
      return arr.compactMap { ($0 as? CKRecordValue).flatMap(decodeFieldValue) }
    }
    return nil
  }

  private static func encodeFieldValue(_ value: Any) -> CKRecordValue? {
    if value is NSNull { return nil }
    if let s = value as? String { return s as CKRecordValue }
    if let n = value as? NSNumber { return n as CKRecordValue }
    if let arr = value as? [Any] {
      return arr.compactMap(encodeFieldValue) as CKRecordValue
    }
    return nil
  }
}
