//
//  AniseekrSubjectLifter.m
//  AniSeekr
//
//  Objective-C bridge header — exposes the Swift subject-lifter module to the
//  React Native runtime so `NativeModules.AniseekrSubjectLifter` resolves at
//  JS load time, along with its `isSupported` constant.
//
//  Generated by plugins/with-subject-lifter.js.
//

#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(AniseekrSubjectLifter, NSObject)

RCT_EXTERN_METHOD(lift:(NSString *)imageUri
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

+ (BOOL)requiresMainQueueSetup { return NO; }

@end
