//
//  AniseekrCloudKitBridge.m
//  AniSeekr
//
//  Objective-C bridge header — exposes the Swift module to the React Native
//  runtime so `NativeModules.AniseekrCloudKitBridge` resolves at JS load time.
//
//  Generated by plugins/with-cloudkit-bridge.js.
//

#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(AniseekrCloudKitBridge, NSObject)

RCT_EXTERN_METHOD(isAvailable:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(fetchAllRecords:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(writeRecords:(NSArray *)records
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(deleteAllRecords:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

+ (BOOL)requiresMainQueueSetup { return NO; }

@end
